name: Publish Story on Itch.io
on: [push, pull_request]

jobs:
  uploadToItchIO:
    name: Upload to Itch.io
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: windows
          ITCH_GAME: the-omniface-war-medieval-level
          ITCH_USER: killerbyte
          PACKAGE: /